---
title: "WuppertalTalk"
author: "Tom Offrede"
date: "2023-06-19"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Temperature data

```{r, include= FALSE}
library(tidyverse)
library(lme4)

load(paste0(here::here(), "/data/tempData-wuppertal.RData"))
```

```{r}
# ggplot(dat, aes(frame, temperature))+
#   geom_point()+
#   geom_path()+
#   geom_smooth(method="lm")+
#   facet_grid(speaker~ROI)
# ggsave(filename = paste0(here::here(), "/figures/temperature/effects.png"),
#        dpi = "retina", width=3000, height=3000, unit="px")
```

```{r}
effT <- data.frame(matrix(nrow=0, ncol=7))
names(effT) <- c("speaker", "condition", "type", "ROI-feat", "direction", "effect", "pORt")

for(s in unique(dat$speaker)){
  for(roi in unique(dat$ROI[dat$speaker==s])){
    c <- broom::tidy(lm(temperature ~ frame + realTemp, dat %>% filter(speaker==s, ROI==roi)))
    est <- c$estimate[2]
    p <- c$p.value[2]
    # ggplot(dat %>% filter(speaker==s, ROI==roi), aes(frame, temperature))+
    #   geom_point()+
    #   geom_smooth(method="lm")+
    #   geom_vline(xintercept=12)+
    #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", p = ", p))
    # ggsave(filename = paste0(paste(here::here(), "figures", "temperature", roi, s, sep="/"), ".png"),
    #        dpi = "retina")
    if(p < 0.05){
      effT[nrow(effT)+1,] <- c(s,
                               unique(dat$condition[dat$speaker==s]),
                               "tempChange",
                               roi,
                               ifelse(est < 0, "negative", "positive"),
                               est,
                               p)
    }
  }
}
```

## Temperature convergence?

```{r}
tempConv <- data.frame(matrix(nrow=0, ncol=6))
names(tempConv) <- c("speaker", "condition", "ROI", "direction", "estimate", "p")

for(s in unique(dat$speaker)){
  for(roi in unique(dat$ROI[dat$speaker==s])){
    if(any(!is.na(dat$tempDiff[dat$speaker==s & dat$ROI==roi]))){
      c <- broom::tidy(lm(tempDiff ~ frame, dat %>% filter(speaker==s, ROI==roi)))
      est <- c$estimate[2]
      p <- c$p.value[2]
      # ggplot(dat %>% filter(speaker==s, ROI==roi), aes(frame, tempDiff))+
      #   geom_point()+
      #   geom_smooth(method="lm")+
      #   geom_vline(xintercept=12)+
      #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", p = ", p))
      # ggsave(filename = paste0(paste(here::here(), "figures", "temperature", "conv", roi, s, sep="/"), ".png"),
      #        dpi = "retina")
      if(p < 0.05){
        tempConv[nrow(tempConv)+1,] <- c(s,
                                         unique(dat$condition[dat$speaker==s]),
                                         roi,
                                         ifelse(est < 0, "negative", "positive"),
                                         est,
                                         p)
      }
    }
  }
}
```


# Speech data

### Turn-level Sychrony: Correlations

```{r, include=FALSE}
folder <- "C:/Users/offredet/Documents/1HU/ExperimentTemperature/Data/SpeechData/"

load(paste0(folder, "data.RData"))

dat <- dat %>% 
  # filter(dyad %in% c("FXO","SGB", "TTY", "ZNV")) %>% 
  mutate(f0meanDiff = abs(turnf0mean - prevTurnf0mean),
         f0medDiff = abs(turnf0med - prevTurnf0med),
         f0sdDiff = abs(turnf0sd - prevTurnf0sd),
         f0maxDiff = abs(turnf0max - prevTurnf0max)) %>% 
  group_by(speaker, task) %>% 
  filter(!duplicated(turn)) %>% 
  mutate(stageTurn = turn / max(turn),
         stage = ifelse(stageTurn <= 0.33, "beginning", ifelse(stageTurn >= 0.66, "ending", NA))) %>% 
  ungroup() %>% 
  filter(task == "D1")

effS <- data.frame(matrix(nrow=0, ncol=7))
names(effS) <- c("speaker", "condition", "type", "ROI-feat", "direction", "effect", "pORt")

effD <- data.frame(matrix(nrow=0, ncol=7))
names(effD) <- c("dyad", "condition", "type", "ROI-feat", "direction", "effect", "pORt")
```

```{r}
for(s in unique(dat$speaker)){
  r <- cor.test(dat$turnf0mean[dat$speaker==s], dat$prevTurnf0mean[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(prevTurnf0mean, turnf0mean, size=turn))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level sync/f0mean/", s, ".png"),
         dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnSync",
                             "f0mean",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$turnf0med[dat$speaker==s], dat$prevTurnf0med[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(prevTurnf0med, turnf0med, size=turn))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level sync/f0med/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnSync",
                             "f0med",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$turnf0sd[dat$speaker==s], dat$prevTurnf0sd[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(prevTurnf0sd, turnf0sd, size=turn))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level sync/f0sd/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnSync",
                             "f0sd",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$turnf0max[dat$speaker==s], dat$prevTurnf0max[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(prevTurnf0max, turnf0max, size=turn))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level sync/f0max/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnSync",
                             "f0max",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
}
```

### Turn-level Convergence: Correlations

```{r}
for(s in unique(dat$speaker)){
  r <- cor.test(dat$f0meanDiff[dat$speaker==s], dat$turn[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(turn, f0meanDiff))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level conv/f0mean/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnConv",
                             "f0mean",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$f0medDiff[dat$speaker==s], dat$turn[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(turn, f0medDiff))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level conv/f0med/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnConv",
                             "f0med",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$f0sdDiff[dat$speaker==s], dat$turn[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(turn, f0sdDiff))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level conv/f0sd/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnConv",
                             "f0sd",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
  
  r <- cor.test(dat$f0maxDiff[dat$speaker==s], dat$turn[dat$speaker==s], method="pearson")
  # ggplot(dat %>% filter(speaker==s), aes(turn, f0maxDiff))+
  #   geom_point()+
  #   geom_smooth(method="lm")+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - r = ", r$estimate, ", p = ", r$p.value))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/turn-level conv/f0max/", s, ".png"),
  #        dpi = "retina")
  if(r$p.value < 0.05){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "turnConv",
                             "f0max",
                             ifelse(r$estimate < 0, "negative", "positive"),
                             r$estimate,
                             r$p.value)
  }
}

```

### Global-level convergence

```{r}
# annotate first 3rd of data set (or first half?) as "beginning" and the last as "ending"
# do t-test or lmer with f0Diff ~ stage (i.e. beginning vs ending)
# visualize with boxplots

dat <- dat %>% 
  filter(!is.na(stage))

for(s in unique(dat$speaker)){
  c <- broom::tidy(lm(f0meanDiff ~ stage, dat %>% filter(speaker==s)))
  est <- c$estimate[2]
  t <- c$statistic[2]
  # ggplot(dat %>% filter(speaker==s), aes(stage, f0meanDiff))+
  #   geom_boxplot()+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", t = ", t))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/global-level conv/f0mean/", s, ".png"),
  #        dpi = "retina")
  if(t > 2){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "globalConv",
                             "f0mean",
                             ifelse(est < 0, "negative", "positive"),
                             est,
                             t)
  }
  
  c <- broom::tidy(lm(f0medDiff ~ stage, dat %>% filter(speaker==s)))
  est <- c$estimate[2]
  t <- c$statistic[2]
  # ggplot(dat %>% filter(speaker==s), aes(stage, f0medDiff))+
  #   geom_boxplot()+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", t = ", t))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/global-level conv/f0med/", s, ".png"),
  #        dpi = "retina")
  if(t > 2){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "globalConv",
                             "f0med",
                             ifelse(est < 0, "negative", "positive"),
                             est,
                             t)
  }
  
  c <- broom::tidy(lm(f0maxDiff ~ stage, dat %>% filter(speaker==s)))
  est <- c$estimate[2]
  t <- c$statistic[2]
  # ggplot(dat %>% filter(speaker==s), aes(stage, f0maxDiff))+
  #   geom_boxplot()+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", t = ", t))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/global-level conv/f0max/", s, ".png"),
  #        dpi = "retina")
  if(t > 2){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "globalConv",
                             "f0max",
                             ifelse(est < 0, "negative", "positive"),
                             est,
                             t)
  }
  
  c <- broom::tidy(lm(f0sdDiff ~ stage, dat %>% filter(speaker==s)))
  est <- c$estimate[2]
  t <- c$statistic[2]
  # ggplot(dat %>% filter(speaker==s), aes(stage, f0sdDiff))+
  #   geom_boxplot()+
  #   ggtitle(paste0(dat$condition[dat$speaker==s], " - est = ", est, ", t = ", t))
  # ggsave(filename = paste0(here::here(), "/figures/individualEffects/global-level conv/f0sd/", s, ".png"),
  #        dpi = "retina")
  if(t > 2){
    effS[nrow(effS)+1,] <- c(s,
                             unique(dat$condition[dat$speaker==s]),
                             "globalConv",
                             "f0sd",
                             ifelse(est < 0, "negative", "positive"),
                             est,
                             t)
  }
}
```

# Join temperature and speech

```{r}
eff <- rbind(effT, effS)
```

